### ISSUE TITLE
该页面加载缓慢

### ISSUE THREAD

**Issue by leov1** [loonggg/CoordinatorLayoutDemo#1]
因为 headLayout.setBackgroundDrawable(new BitmapDrawable(BlurUtil.fastblur(this, bitmap, 180)));
和  collapsingToolbarLayout.setContentScrim(new BitmapDrawable(BlurUtil.fastblur(this,bitmap,180)));
中 BlurUtil.fastblur() 方法 耗时比较久，会导致 启动该页面 ，元素显示 延迟大概8秒左右

**Comment by loonggg** [comment]
目前确实有这个问题。你有好的解决方案么？

**Comment by leov1** [comment]
https://gist.github.com/leov1/4b249af5e9dc2d7e2c7c9ba20475c47a  可以看一下这个，处理时间 节约了几秒，但是还有有延迟，使用JNI 是否会 更 快一些。。

**Comment by loonggg** [comment]
已经修改了毛玻璃加载显示慢，白屏一会的问题。可以再来看看了。
